server:
  port: 8085
spring:
  application:
    name: cloudfeign
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
feign:
  hystrix:
    enabled: true
